sqlite_path = "app_data.db"  # Always end with .db extension

fact_claims_query = """
SELECT 
    ENCOUNTER_ID,
    ENCOUNTER_GROUP_SK,
    ENCOUNTER_TYPE_SK,
    PRIMARY_DIAGNOSIS_CODE,
    PRIMARY_DIAGNOSIS_DESCRIPTION,
    CCSR_PARENT_CATEGORY,
    CCSR_CATEGORY,
    CCSR_CATEGORY_DESCRIPTION,
    PERSON_ID,
    YEAR_MONTH,
    SERVICE_CATEGORY_SK,
    CLAIM_ID,
    CLAIM_TYPE,
    PAID_AMOUNT
FROM FACT_CLAIMS LIMIT 100000
"""
fact_member_months_query = """
SELECT
    PERSON_ID,
    YEAR_NBR,
    YEAR_MONTH,
    MEMBER_MONTHS,
    TOTAL_YEAR_MONTHS,
    MONTHALLOCATIONFACTOR,
    DATA_SOURCE,
    PATIENT_SOURCE_KEY,
    PAYER,
    PLAN,
    NORMALIZED_RISK_SCORE,
    POPULATION_NORMALIZED_RISK_SCORE
FROM FACT_MEMBER_MONTHS LIMIT 100000
"""

fact_expected_values_query = """
SELECT
    YEAR_NBR,
    PERSON_ID,
    PAYER,
    PLAN,
    DATA_SOURCE,
    PAID_AMOUNT_PRED,
    OUTPATIENT_PAID_AMOUNT_PRED,
    OTHER_PAID_AMOUNT_PRED,
    OFFICE_BASED_PAID_AMOUNT_PRED,
    INPATIENT_PAID_AMOUNT_PRED,
    OUTPATIENT_INJECTIONS_PAID_AMOUNT_PRED,
    EMERGENCY_DEPARTMENT_PAID_AMOUNT_PRED,
    OUTPATIENT_RADIOLOGY_PAID_AMOUNT_PRED,
    OUTPATIENT_PT_OT_ST_PAID_AMOUNT_PRED,
    OUTPATIENT_HOSPICE_PAID_AMOUNT_PRED,
    URGENT_CARE_PAID_AMOUNT_PRED,
    OUTPATIENT_HOSPITAL_OR_CLINIC_PAID_AMOUNT_PRED,
    HOME_HEALTH_PAID_AMOUNT_PRED,
    DIALYSIS_PAID_AMOUNT_PRED,
    OUTPATIENT_REHABILITATION_PAID_AMOUNT_PRED,
    OUTPATIENT_SURGERY_PAID_AMOUNT_PRED,
    AMBULATORY_SURGERY_CENTER_PAID_AMOUNT_PRED,
    OUTPATIENT_PSYCH_PAID_AMOUNT_PRED,
    DME_ORPHANED_PAID_AMOUNT_PRED,
    ORPHANED_CLAIM_PAID_AMOUNT_PRED,
    AMBULANCE_ORPHANED_PAID_AMOUNT_PRED,
    LAB_ORPHANED_PAID_AMOUNT_PRED,
    OFFICE_VISIT_RADIOLOGY_PAID_AMOUNT_PRED,
    OFFICE_VISIT_PAID_AMOUNT_PRED,
    OFFICE_VISIT_SURGERY_PAID_AMOUNT_PRED,
    OFFICE_VISIT_OTHER_PAID_AMOUNT_PRED,
    TELEHEALTH_PAID_AMOUNT_PRED,
    OFFICE_VISIT_PT_OT_ST_PAID_AMOUNT_PRED,
    OFFICE_VISIT_INJECTIONS_PAID_AMOUNT_PRED,
    ACUTE_INPATIENT_PAID_AMOUNT_PRED,
    INPATIENT_HOSPICE_PAID_AMOUNT_PRED,
    INPATIENT_PSYCH_PAID_AMOUNT_PRED,
    INPATIENT_REHABILITATION_PAID_AMOUNT_PRED,
    INPATIENT_SKILLED_NURSING_PAID_AMOUNT_PRED,
    COUNT_PRED,
    INPATIENT_COUNT_PRED,
    OFFICE_BASED_COUNT_PRED,
    OTHER_COUNT_PRED,
    OUTPATIENT_COUNT_PRED,
    OUTPATIENT_INJECTIONS_COUNT_PRED,
    EMERGENCY_DEPARTMENT_COUNT_PRED,
    OUTPATIENT_RADIOLOGY_COUNT_PRED,
    OUTPATIENT_PT_OT_ST_COUNT_PRED,
    OUTPATIENT_HOSPICE_COUNT_PRED,
    URGENT_CARE_COUNT_PRED,
    OUTPATIENT_HOSPITAL_OR_CLINIC_COUNT_PRED,
    HOME_HEALTH_COUNT_PRED,
    DIALYSIS_COUNT_PRED,
    OUTPATIENT_REHABILITATION_COUNT_PRED,
    OUTPATIENT_SURGERY_COUNT_PRED,
    AMBULATORY_SURGERY_CENTER_COUNT_PRED,
    OUTPATIENT_PSYCH_COUNT_PRED,
    DME_ORPHANED_COUNT_PRED,
    ORPHANED_CLAIM_COUNT_PRED,
    AMBULANCE_ORPHANED_COUNT_PRED,
    LAB_ORPHANED_COUNT_PRED,
    OFFICE_VISIT_RADIOLOGY_COUNT_PRED,
    OFFICE_VISIT_COUNT_PRED,
    OFFICE_VISIT_SURGERY_COUNT_PRED,
    OFFICE_VISIT_OTHER_COUNT_PRED,
    TELEHEALTH_COUNT_PRED,
    OFFICE_VISIT_PT_OT_ST_COUNT_PRED,
    OFFICE_VISIT_INJECTIONS_COUNT_PRED,
    ACUTE_INPATIENT_COUNT_PRED,
    INPATIENT_HOSPICE_COUNT_PRED,
    INPATIENT_PSYCH_COUNT_PRED,
    INPATIENT_REHABILITATION_COUNT_PRED,
    INPATIENT_SKILLED_NURSING_COUNT_PRED
FROM FACT_EXPECTED_VALUES
"""

dim_encounter_group_query = """
SELECT
    ENCOUNTER_GROUP,
    ENCOUNTER_GROUP_SK
FROM DIM_ENCOUNTER_GROUP
"""

dim_encounter_type_query = """
SELECT
    ENCOUNTER_TYPE,
    ENCOUNTER_TYPE_SK,
    ENCOUNTER_GROUP_SK
FROM DIM_ENCOUNTER_TYPE
"""

dim_member = """
SELECT 
    PERSON_ID,
    SEX,
    AGE
FROM DIM_MEMBER
"""

table_list = [
    {"table_name": "FACT_CLAIMS", "query": fact_claims_query},
    {"table_name": "FACT_MEMBER_MONTHS", "query": fact_member_months_query},
    {"table_name": "DIM_ENCOUNTER_GROUP", "query": dim_encounter_group_query},
    {"table_name": "DIM_ENCOUNTER_TYPE", "query": dim_encounter_type_query},
    {"table_name": "DIM_MEMBER", "query": dim_member},
    {"table_name": "FACT_EXPECTED_VALUES", "query": fact_expected_values_query},
]
